# Generated by Django 4.2.7 on 2025-11-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profil_id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "profils",
            },
        ),
    ]
