# Generated by Django 4.2.7 on 2026-02-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                db_column="id_user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="profile",
            field=models.OneToOneField(
                limit_choices_to={"role__name": "PATIENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_profile",
                to="profiles.profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="profile",
            unique_together={("user", "role")},
        ),
    ]
