# Generated by Django 4.2.7 on 2026-01-02 19:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("glycemia_value", models.IntegerField()),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("inapp_created_at", models.DateTimeField(blank=True, null=True)),
                ("push_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIGGERED", "TRIGGERED"),
                            ("SENT", "SENT"),
                            ("ACKED", "ACKED"),
                            ("RESOLVED", "RESOLVED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="TRIGGERED",
                        max_length=20,
                    ),
                ),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "alert_events",
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("min_glycemia", models.IntegerField(blank=True, null=True)),
                ("max_glycemia", models.IntegerField(blank=True, null=True)),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "INFO"),
                            (2, "LOW"),
                            (3, "MEDIUM"),
                            (4, "HIGH"),
                            (5, "CRITICAL"),
                        ],
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "alert_rules",
            },
        ),
        migrations.CreateModel(
            name="UserAlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("min_glycemia_override", models.IntegerField(blank=True, null=True)),
                ("max_glycemia_override", models.IntegerField(blank=True, null=True)),
                ("cooldown_seconds", models.PositiveIntegerField(default=600)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_rules",
                        to="alerts.alertrule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_alert_rules",
            },
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(fields=["code"], name="alert_rules_code_77ebdb_idx"),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["severity"], name="alert_rules_severit_b37e4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["is_active"], name="alert_rules_is_acti_699c44_idx"
            ),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="alerts.alertrule",
            ),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="useralertrule",
            index=models.Index(
                fields=["user", "enabled"], name="user_alert__user_id_9f6bfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useralertrule",
            index=models.Index(
                fields=["rule", "enabled"], name="user_alert__rule_id_f27c82_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="useralertrule",
            constraint=models.UniqueConstraint(
                fields=("user", "rule"), name="uniq_user_rule"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["user", "-triggered_at"], name="alert_event_user_id_802393_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["rule", "-triggered_at"], name="alert_event_rule_id_c328fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["status", "-triggered_at"], name="alert_event_status_d6b77f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["user", "rule", "-triggered_at"],
                name="alert_event_user_id_62dad2_idx",
            ),
        ),
    ]
