# Generated by Django 4.2.7 on 2026-02-13 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("glycemia_value", models.IntegerField()),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("inapp_created_at", models.DateTimeField(blank=True, null=True)),
                ("push_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIGGERED", "TRIGGERED"),
                            ("SENT", "SENT"),
                            ("TREATING", "TREATING"),
                            ("ACKED", "ACKED"),
                            ("RESOLVED", "RESOLVED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="TRIGGERED",
                        max_length=20,
                    ),
                ),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "alert_events",
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("min_glycemia", models.IntegerField(blank=True, null=True)),
                ("max_glycemia", models.IntegerField(blank=True, null=True)),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "INFO"),
                            (2, "LOW"),
                            (3, "MEDIUM"),
                            (4, "HIGH"),
                            (5, "CRITICAL"),
                        ],
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "alert_rules",
            },
        ),
        migrations.CreateModel(
            name="UserAlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("min_glycemia_override", models.IntegerField(blank=True, null=True)),
                ("max_glycemia_override", models.IntegerField(blank=True, null=True)),
                ("cooldown_seconds", models.PositiveIntegerField(default=600)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_rules",
                        to="alerts.alertrule",
                    ),
                ),
            ],
            options={
                "db_table": "user_alert_rules",
            },
        ),
    ]
