# Generated by Django 4.2.7 on 2026-01-31 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useralertrule",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(fields=["code"], name="alert_rules_code_77ebdb_idx"),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["severity"], name="alert_rules_severit_b37e4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["is_active"], name="alert_rules_is_acti_699c44_idx"
            ),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="alerts.alertrule",
            ),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="useralertrule",
            index=models.Index(
                fields=["user", "enabled"], name="user_alert__user_id_9f6bfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useralertrule",
            index=models.Index(
                fields=["rule", "enabled"], name="user_alert__rule_id_f27c82_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="useralertrule",
            constraint=models.UniqueConstraint(
                fields=("user", "rule"), name="uniq_user_rule"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["user", "-triggered_at"], name="alert_event_user_id_802393_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["rule", "-triggered_at"], name="alert_event_rule_id_c328fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["status", "-triggered_at"], name="alert_event_status_d6b77f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["user", "rule", "-triggered_at"],
                name="alert_event_user_id_62dad2_idx",
            ),
        ),
    ]
