# Generated by Django 4.2.7 on 2025-12-07 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWidgetLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("widget_id", models.CharField(max_length=50)),
                ("column", models.IntegerField(default=0)),
                ("row", models.IntegerField(default=0)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("compact", "Compact"),
                            ("normal", "Normal"),
                            ("expanded", "Expanded"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widget_layouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_widget_layouts",
                "unique_together": {("user", "widget_id")},
            },
        ),
        migrations.CreateModel(
            name="UserWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("widget_id", models.CharField(max_length=50)),
                ("visible", models.BooleanField(default=True)),
                (
                    "refresh_interval",
                    models.IntegerField(
                        default=300, help_text="Refresh interval in seconds"
                    ),
                ),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_widgets",
                "unique_together": {("user", "widget_id")},
            },
        ),
    ]
