# Generated by Django 4.2.7 on 2026-01-29 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwidgetlayout",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widget_layouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userwidget",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_widgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userwidgetlayout",
            index=models.Index(
                fields=["user", "column", "row"], name="user_widget_user_id_f06e6b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userwidgetlayout",
            constraint=models.UniqueConstraint(
                fields=("user", "widget_id"), name="uniq_user_widget_layout"
            ),
        ),
        migrations.AddIndex(
            model_name="userwidget",
            index=models.Index(
                fields=["user", "visible"], name="user_widget_user_id_989718_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userwidget",
            constraint=models.UniqueConstraint(
                fields=("user", "widget_id"), name="uniq_user_widget"
            ),
        ),
    ]
