# Generated by Django 4.2.7 on 2025-11-20 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_role_field"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
