# Generated by Django 4.2.7 on 2026-01-20 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0003_delete_doctorpatient"),
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="medical_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Doctor associated with this patient (One doctor per patient)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="doctors.doctor",
            ),
        ),
    ]
