# Generated by Django 4.2.7 on 2026-02-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("medication_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("dosage", models.CharField(blank=True, max_length=100, null=True)),
                ("interval_h", models.IntegerField(blank=True, null=True)),
                ("max_duration_d", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "medications",
            },
        ),
        migrations.CreateModel(
            name="UserMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("statut", models.BooleanField(default=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_medications",
                        to="medications.medication",
                    ),
                ),
            ],
            options={
                "db_table": "user_medications",
            },
        ),
    ]
