# Generated by Django 4.2.7 on 2026-03-09 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermedication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_medications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicationschedule",
            name="user_medication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="medications.usermedication",
            ),
        ),
        migrations.AddField(
            model_name="medicationintake",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intakes",
                to="medications.medicationschedule",
            ),
        ),
        migrations.AddField(
            model_name="medicationintake",
            name="user_medication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intakes",
                to="medications.usermedication",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="medicationschedule",
            unique_together={("user_medication", "time")},
        ),
        migrations.AlterUniqueTogether(
            name="medicationintake",
            unique_together={("user_medication", "scheduled_date", "scheduled_time")},
        ),
    ]
