# Generated by Django 4.2.7 on 2026-05-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="dosage",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="medication",
            name="type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="usermedication",
            name="custom_dosage",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="usermedication",
            name="custom_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
