# Generated by Django 4.2.7 on 2026-05-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medications", "0003_remove_null_from_charfields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="form",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="medication",
            name="route",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
