# Generated by Django 4.2.7 on 2026-02-05 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("cgm", "CGM"),
                            ("manual", "Manual"),
                            ("simulator", "Simulator"),
                        ],
                        default="cgm",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("dexcom", "Dexcom"),
                            ("freestyle", "FreeStyle Libre"),
                            ("simulator", "Simulator"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sampling_interval_sec",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("timezone", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "devices",
                "ordering": ["-created_at"],
            },
        ),
    ]
