FROM node:20-alpine

WORKDIR /app

# Copier package.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY . .

# Variables d'environnement
ENV FAST_REFRESH=false
ENV SKIP_PREFLIGHT_CHECK=true

EXPOSE 3000

CMD ["npm", "start"]