# Generated by Django 4.2.7 on 2026-05-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("meal_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("ingredients", models.TextField(blank=True, null=True)),
                ("recipe", models.TextField(blank=True, null=True)),
                ("glucose", models.FloatField(blank=True, null=True)),
                ("calories", models.IntegerField(blank=True, null=True)),
                ("glucides", models.FloatField(blank=True, null=True)),
                ("proteines", models.FloatField(blank=True, null=True)),
                ("lipides", models.FloatField(blank=True, null=True)),
                ("link_photo", models.URLField(blank=True, null=True)),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manuel"), ("openfood", "Open Food Facts")],
                        default="manual",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "meals",
            },
        ),
        migrations.CreateModel(
            name="UserMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taken_at", models.DateTimeField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Petit-déjeuner"),
                            ("lunch", "Déjeuner"),
                            ("snack", "Collation"),
                            ("dinner", "Dîner"),
                        ],
                        default="lunch",
                        max_length=15,
                    ),
                ),
                ("portion_g", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "input_mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manuel"),
                            ("barcode", "Code-barres"),
                            ("search", "Recherche"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_meals",
                        to="meals.meal",
                    ),
                ),
            ],
            options={
                "db_table": "users_meals",
            },
        ),
    ]
