# Generated by Django 4.2.7 on 2026-01-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("meal_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("ingredients", models.TextField(blank=True, null=True)),
                ("recipe", models.TextField(blank=True, null=True)),
                ("glucose", models.FloatField(blank=True, null=True)),
                ("calories", models.IntegerField(blank=True, null=True)),
                ("link_photo", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "meals",
            },
        ),
        migrations.CreateModel(
            name="UserMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taken_at", models.DateTimeField()),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_meals",
                        to="meals.meal",
                    ),
                ),
            ],
            options={
                "db_table": "users_meals",
            },
        ),
    ]
