# Generated by Django 4.2.7 on 2026-02-05 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermeal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_meals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usermeal",
            unique_together={("user", "meal", "taken_at")},
        ),
    ]
