# Generated by Django 4.2.7 on 2026-05-23 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0003_sync_meals_db_columns"),
        ("meals", "0004_reconcile_remaining_usermeal_fields"),
    ]

    operations = []
