# Generated by Django 4.2.7 on 2026-05-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("activity_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("recommended_duration", models.IntegerField(blank=True, null=True)),
                ("calories_burned", models.IntegerField(blank=True, null=True)),
                ("sugar_used", models.FloatField(blank=True, null=True)),
                ("link_photo", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "activities",
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("intensity", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "user_activity",
            },
        ),
        migrations.CreateModel(
            name="UserMilestonePoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "user_milestone_points",
            },
        ),
        migrations.CreateModel(
            name="UserStepDayCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("last_reported_steps", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "user_step_day_checkpoint",
            },
        ),
    ]
