# Generated by Django 4.2.7 on 2026-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="steps",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
