# Generated by Django 4.2.7 on 2026-01-31 21:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "doctor_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "medical_center_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom du Cabinet / Hôpital",
                    ),
                ),
                (
                    "medical_center_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Adresse du Cabinet / Hôpital",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Doctor Profile",
                "verbose_name_plural": "Doctor Profiles",
                "db_table": "doctor_profiles",
            },
        ),
        migrations.CreateModel(
            name="InvitationStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Invitation Status",
                "verbose_name_plural": "Invitation Statuses",
                "db_table": "invitation_statuses",
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id_specialty",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Specialty Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Specialty",
                "verbose_name_plural": "Specialties",
                "db_table": "specialties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VerificationStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Verification Status",
                "verbose_name_plural": "Verification Statuses",
                "db_table": "verification_statuses",
            },
        ),
        migrations.CreateModel(
            name="PatientCareTeam",
            fields=[
                (
                    "id_team_member",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invitation_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Invitation Email (for Pending Doctors)",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Relation Type (e.g. Father, Mother)",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("REFERENT_DOCTOR", "Referent Doctor"),
                            ("SPECIALIST", "Specialist"),
                            ("NURSE", "Nurse"),
                            ("FAMILY", "Family"),
                            ("CAREGIVER", "Caregiver"),
                        ],
                        max_length=50,
                        verbose_name="Role in Team",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_care_team_members",
                        to="doctors.doctorprofile",
                        verbose_name="Approved By (Doctor)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Care Team Member",
                "verbose_name_plural": "Patient Care Team",
                "db_table": "patient_care_team",
            },
        ),
    ]
