# Generated by Django 4.2.7 on 2026-02-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcareteam",
            name="member_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="care_teams_as_member",
                to="profiles.profile",
                verbose_name="Team Member (Doctor/Family)",
            ),
        ),
        migrations.AddField(
            model_name="patientcareteam",
            name="patient_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="care_team_members",
                to="profiles.patientprofile",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="patientcareteam",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="care_team_entries",
                to="doctors.invitationstatus",
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="profile",
            field=models.OneToOneField(
                limit_choices_to={"role__name": "DOCTOR"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctors",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="verification_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doctors",
                to="doctors.verificationstatus",
            ),
        ),
    ]
