# Generated by Django 4.2.7 on 2026-01-29 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="verified_by_user",
            field=models.ForeignKey(
                blank=True,
                db_column="verified_by_user_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_doctors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
