# Generated by Django 4.2.7 on 2026-01-20 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0002_doctorpatient"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DoctorPatient",
        ),
    ]
