# Generated by Django 4.2.7 on 2026-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcareteam",
            name="rejection_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Rejection Reason"
            ),
        ),
    ]
