# Generated by Django 4.2.7 on 2026-05-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0004_patientcareteam_rejection_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientcareteam",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
