# Generated by Django 4.2.7 on 2025-11-07 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Glycemia",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("measured_at", models.DateTimeField()),
                ("value", models.FloatField()),
            ],
            options={
                "db_table": "glycemia",
            },
        ),
        migrations.CreateModel(
            name="GlycemiaHisto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("measured_at", models.DateTimeField(db_index=True)),
                ("value", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glycemia_histo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "glycemia_histo",
                "indexes": [
                    models.Index(
                        fields=["user", "measured_at"],
                        name="glycemia_hi_user_id_0811c0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GlycemiaDataIA",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("measured_at", models.DateTimeField(db_index=True)),
                ("value", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glycemia_ai",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "glycemia_data_ia",
                "indexes": [
                    models.Index(
                        fields=["user", "measured_at"],
                        name="glycemia_da_user_id_755843_idx",
                    )
                ],
            },
        ),
    ]
