# Generated by Django 4.2.7 on 2025-12-11 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlycemiaHisto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reading_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("measured_at", models.DateTimeField(db_index=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
                ("unit", models.CharField(default="mg/dL", max_length=10)),
                (
                    "trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rising", "Rising"),
                            ("falling", "Falling"),
                            ("flat", "Flat"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("rate", models.FloatField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("cgm", "CGM"), ("manual", "Manual")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fasting", "Fasting"),
                            ("preprandial", "Preprandial"),
                            ("postprandial_1h", "Postprandial 1h"),
                            ("postprandial_2h", "Postprandial 2h"),
                            ("bedtime", "Bedtime"),
                            ("exercise", "Exercise"),
                            ("stress", "Stress"),
                            ("correction", "Correction"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("photo_url", models.URLField(blank=True, null=True)),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lng", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glycemia_histo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "glycemia_histo",
                "ordering": ["-measured_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "measured_at"],
                        name="glycemia_hi_user_id_0811c0_idx",
                    ),
                    models.Index(
                        fields=["user", "source", "measured_at"],
                        name="glycemia_hi_user_id_3f321f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GlycemiaDataIA",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("prediction_start", models.DateTimeField(blank=True, null=True)),
                ("prediction_end", models.DateTimeField(blank=True, null=True)),
                ("prob_hypo", models.FloatField(blank=True, null=True)),
                ("prob_hyper", models.FloatField(blank=True, null=True)),
                ("recommendation", models.TextField(blank=True, null=True)),
                (
                    "model_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glycemia_ai",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "glycemia_data_ia",
                "indexes": [
                    models.Index(
                        fields=["user", "prediction_start"],
                        name="glycemia_da_user_id_b28abd_idx",
                    ),
                    models.Index(
                        fields=["user", "prediction_end"],
                        name="glycemia_da_user_id_5ac467_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Glycemia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measured_at", models.DateTimeField()),
                ("value", models.FloatField()),
                ("unit", models.CharField(default="mg/dL", max_length=10)),
                (
                    "trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rising", "Rising"),
                            ("falling", "Falling"),
                            ("flat", "Flat"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "rate",
                    models.FloatField(
                        blank=True, help_text="mg/dL per minute", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("cgm", "CGM"), ("manual", "Manual")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glycemia_month",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "glycemia",
                "ordering": ["-measured_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "measured_at"],
                        name="glycemia_user_id_8aae7b_idx",
                    )
                ],
            },
        ),
    ]
