# Generated by Django 4.2.7 on 2026-02-13 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Glycemia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measured_at", models.DateTimeField()),
                ("value", models.FloatField()),
                ("unit", models.CharField(default="mg/dL", max_length=10)),
                (
                    "trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rising", "Rising"),
                            ("falling", "Falling"),
                            ("flat", "Flat"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "rate",
                    models.FloatField(
                        blank=True, help_text="mg/dL per minute", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("cgm", "CGM"), ("manual", "Manual")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fasting", "Fasting"),
                            ("preprandial", "Preprandial"),
                            ("postprandial_1h", "Postprandial 1h"),
                            ("postprandial_2h", "Postprandial 2h"),
                            ("bedtime", "Bedtime"),
                            ("exercise", "Exercise"),
                            ("stress", "Stress"),
                            ("correction", "Correction"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "glycemia",
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="GlycemiaDataIA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "for_time",
                    models.DateTimeField(
                        db_index=True, help_text="Instant de référence prédit (t=0)"
                    ),
                ),
                (
                    "input_start",
                    models.DateTimeField(
                        help_text="Début de la fenêtre d'entrée (ex : t − 2 h)"
                    ),
                ),
                (
                    "input_end",
                    models.DateTimeField(
                        help_text="Fin de la fenêtre d'entrée (ex : t)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model_version", models.CharField(db_index=True, max_length=64)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("baseline", "Baseline"),
                            ("lstm", "LSTM"),
                            ("transformer", "Transformer"),
                            ("ensemble", "Ensemble"),
                        ],
                        db_index=True,
                        default="baseline",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("low_confidence", "Low Confidence"),
                            ("insufficient_data", "Insufficient Data"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="ok",
                        max_length=20,
                    ),
                ),
                (
                    "runtime_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Durée de la prédiction en millisecondes",
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Score de confiance global agrégé (0..1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "input_readings_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre de lectures de glycémie utilisées en entrée",
                        null=True,
                    ),
                ),
                (
                    "missing_ratio",
                    models.FloatField(
                        blank=True,
                        help_text="Ratio de données manquantes dans la fenêtre (0..1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "features_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash du vecteur de features pour reproductibilité",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("y_hat_15", models.FloatField(blank=True, null=True)),
                ("p10_15", models.FloatField(blank=True, null=True)),
                ("p90_15", models.FloatField(blank=True, null=True)),
                ("y_hat_30", models.FloatField(blank=True, null=True)),
                ("p10_30", models.FloatField(blank=True, null=True)),
                ("p90_30", models.FloatField(blank=True, null=True)),
                ("y_hat_60", models.FloatField(blank=True, null=True)),
                ("p10_60", models.FloatField(blank=True, null=True)),
                ("p90_60", models.FloatField(blank=True, null=True)),
                (
                    "risk_hypo_15",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "risk_hyper_15",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "risk_hypo_30",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "risk_hyper_30",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "risk_hypo_60",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "risk_hyper_60",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("recommendation", models.TextField(blank=True, null=True)),
                ("meta_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "glycemia_data_ia",
                "ordering": ["-for_time"],
            },
        ),
        migrations.CreateModel(
            name="GlycemiaHisto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reading_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("measured_at", models.DateTimeField(db_index=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
                ("unit", models.CharField(default="mg/dL", max_length=10)),
                (
                    "trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rising", "Rising"),
                            ("falling", "Falling"),
                            ("flat", "Flat"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("rate", models.FloatField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("cgm", "CGM"), ("manual", "Manual")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fasting", "Fasting"),
                            ("preprandial", "Preprandial"),
                            ("postprandial_1h", "Postprandial 1h"),
                            ("postprandial_2h", "Postprandial 2h"),
                            ("bedtime", "Bedtime"),
                            ("exercise", "Exercise"),
                            ("stress", "Stress"),
                            ("correction", "Correction"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("photo_url", models.URLField(blank=True, null=True)),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lng", models.FloatField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="glycemia_histo",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "glycemia_histo",
                "ordering": ["-measured_at"],
            },
        ),
    ]
