# Generated by Django 4.2.7 on 2025-12-04 11:11

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("glycemia", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glycemiahisto",
            options={"ordering": ["-measured_at"]},
        ),
        migrations.AddField(
            model_name="glycemia",
            name="rate",
            field=models.FloatField(
                blank=True, help_text="mg/dL per minute", null=True
            ),
        ),
        migrations.AddField(
            model_name="glycemia",
            name="source",
            field=models.CharField(
                choices=[("cgm", "CGM"), ("manual", "Manual")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="glycemia",
            name="trend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rising", "Rising"),
                    ("falling", "Falling"),
                    ("flat", "Flat"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="glycemia",
            name="unit",
            field=models.CharField(default="mg/dL", max_length=10),
        ),
        migrations.AddField(
            model_name="glycemiadataia",
            name="model_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="glycemiadataia",
            name="prediction_window",
            field=models.IntegerField(blank=True, help_text="Minutes", null=True),
        ),
        migrations.AddField(
            model_name="glycemiadataia",
            name="prob_hyper",
            field=models.FloatField(blank=True, help_text="Probability 0-1", null=True),
        ),
        migrations.AddField(
            model_name="glycemiadataia",
            name="prob_hypo",
            field=models.FloatField(blank=True, help_text="Probability 0-1", null=True),
        ),
        migrations.AddField(
            model_name="glycemiadataia",
            name="recommendation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glycemiahisto",
            name="context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fasting", "Fasting"),
                    ("preprandial", "Preprandial"),
                    ("postprandial_1h", "Postprandial 1h"),
                    ("postprandial_2h", "Postprandial 2h"),
                    ("bedtime", "Bedtime"),
                    ("exercise", "Exercise"),
                    ("stress", "Stress"),
                    ("correction", "Correction"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="glycemiahisto",
            name="location_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glycemiahisto",
            name="location_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glycemiahisto",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glycemiahisto",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glycemiahisto",
            name="rate",
            field=models.FloatField(
                blank=True, help_text="mg/dL per minute", null=True
            ),
        ),
        migrations.AddField(
            model_name="glycemiahisto",
            name="reading_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="glycemiahisto",
            name="recorded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 12, 4, 11, 11, 52, 926151, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="glycemiahisto",
            name="source",
            field=models.CharField(
                choices=[("cgm", "CGM"), ("manual", "Manual")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="glycemiahisto",
            name="trend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rising", "Rising"),
                    ("falling", "Falling"),
                    ("flat", "Flat"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="glycemiahisto",
            name="unit",
            field=models.CharField(default="mg/dL", max_length=10),
        ),
        migrations.AddIndex(
            model_name="glycemiahisto",
            index=models.Index(
                fields=["user", "source", "measured_at"],
                name="glycemia_hi_user_id_3f321f_idx",
            ),
        ),
    ]
