# Generated by Django 4.2.7 on 2026-01-31 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0002_initial"),
        ("glycemia", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="glycemiahisto",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="glycemia_histo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="glycemiadataia",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="glycemia_ai_runs",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="glycemiadataia",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="glycemia_ai",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="glycemia",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="glycemia_cache",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="glycemia",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="glycemia_month",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="glycemiahisto",
            index=models.Index(
                fields=["user", "measured_at"], name="glycemia_hi_user_id_0811c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="glycemiahisto",
            index=models.Index(
                fields=["user", "source", "measured_at"],
                name="glycemia_hi_user_id_3f321f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="glycemiahisto",
            index=models.Index(
                fields=["user", "device", "measured_at"],
                name="glycemia_hi_user_id_252148_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="glycemiadataia",
            index=models.Index(
                fields=["user", "-for_time"], name="glycemia_da_user_id_a61c99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="glycemiadataia",
            index=models.Index(
                fields=["user", "device", "-for_time"],
                name="glycemia_da_user_id_ad03c3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="glycemiadataia",
            constraint=models.UniqueConstraint(
                fields=("user", "for_time", "model_version"),
                name="uniq_glycemia_ia_run_user_time_model",
            ),
        ),
        migrations.AddIndex(
            model_name="glycemia",
            index=models.Index(
                fields=["user", "measured_at"], name="glycemia_user_id_8aae7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="glycemia",
            index=models.Index(
                fields=["user", "device", "measured_at"],
                name="glycemia_user_id_5c9360_idx",
            ),
        ),
    ]
