# Generated by Django 4.2.7 on 2026-01-29 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("glycemia", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="glycemiahisto",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="glycemia_histo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="glycemiadataia",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="glycemia_ai",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="glycemia",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="glycemia_month",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="glycemiahisto",
            index=models.Index(
                fields=["user", "measured_at"], name="glycemia_hi_user_id_0811c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="glycemiahisto",
            index=models.Index(
                fields=["user", "source", "measured_at"],
                name="glycemia_hi_user_id_3f321f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="glycemiadataia",
            index=models.Index(
                fields=["user", "prediction_start"],
                name="glycemia_da_user_id_b28abd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="glycemiadataia",
            index=models.Index(
                fields=["user", "prediction_end"], name="glycemia_da_user_id_5ac467_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="glycemia",
            index=models.Index(
                fields=["user", "measured_at"], name="glycemia_user_id_8aae7b_idx"
            ),
        ),
    ]
