# Generated by Django 4.2.7 on 2025-12-05 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glycemia", "0002_alter_glycemiahisto_options_glycemia_rate_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="glycemiadataia",
            name="glycemia_da_user_id_755843_idx",
        ),
        migrations.RemoveField(
            model_name="glycemiadataia",
            name="measured_at",
        ),
        migrations.RemoveField(
            model_name="glycemiadataia",
            name="prediction_window",
        ),
        migrations.RemoveField(
            model_name="glycemiadataia",
            name="value",
        ),
        migrations.AddField(
            model_name="glycemiadataia",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 12, 5, 13, 13, 27, 840124, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="glycemiadataia",
            name="prediction_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glycemiadataia",
            name="prediction_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="glycemiadataia",
            name="prob_hyper",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="glycemiadataia",
            name="prob_hypo",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="glycemiahisto",
            name="rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="glycemiadataia",
            index=models.Index(
                fields=["user", "prediction_start"],
                name="glycemia_da_user_id_b28abd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="glycemiadataia",
            index=models.Index(
                fields=["user", "prediction_end"], name="glycemia_da_user_id_5ac467_idx"
            ),
        ),
    ]
