# Generated by Django 4.2.7 on 2026-02-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glycemia", "0002_initial"),
    ]

    operations = [
        # context and notes columns are missing from the glycemia table
        # even though the initial migration declared them — use AddField
        migrations.AddField(
            model_name="glycemia",
            name="context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fasting", "Fasting"),
                    ("preprandial", "Preprandial"),
                    ("postprandial_1h", "Postprandial 1h"),
                    ("postprandial_2h", "Postprandial 2h"),
                    ("bedtime", "Bedtime"),
                    ("exercise", "Exercise"),
                    ("stress", "Stress"),
                    ("correction", "Correction"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="glycemia",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        # glycemia_histo already has these columns — just alter
        migrations.AlterField(
            model_name="glycemiahisto",
            name="context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fasting", "Fasting"),
                    ("preprandial", "Preprandial"),
                    ("postprandial_1h", "Postprandial 1h"),
                    ("postprandial_2h", "Postprandial 2h"),
                    ("bedtime", "Bedtime"),
                    ("exercise", "Exercise"),
                    ("stress", "Stress"),
                    ("correction", "Correction"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="glycemiahisto",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
