name: Deploy Frontend Web (S3)

on:
  push:
    branches: [ main, feat/deploy-complete-b ]
    paths:
      - 'frontend_web/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd frontend_web
          npm install --legacy-peer-deps

      - name: Build for Production
        env:
          # Ici on injecte l'URL de l'ALB (Plan B)
          # Si tu veux switcher sur le Plan A, tu changeras cette valeur ici
          VITE_API_URL: "http://glycopilot-alb-1175156610.eu-west-3.elb.amazonaws.com/api"
        run: |
          cd frontend_web
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Deploy to S3
        run : |
          aws s3 sync ./frontend_web/dist/ s3://glycopilot-web-frontend-958587270787/ --delete